### ISSUE TITLE
Is it possible to set knownRegions and region for localization?

### ISSUE THREAD

**Issue by DracoBlue** [CocoaPods/Xcodeproj#217] opened 2014-10-30 14:02 UTC
I try to use xcodeproj to modify the localization settings in xcode. I come from a cordova/phonegap background. 

I want to get rid of the wrong languages here:
![bildschirmfoto 2014-10-30 um 15 00 32](https://cloud.githubusercontent.com/assets/35926/4844544/3541b91a-603d-11e4-84c8-2a78b1ba7b0e.png)

In the Info.plist file it's a key called knownRegions, but I cannot find the proper path in xcodeproj's plist.

**Comment by kylef** [comment] 2015-01-31 22:28
Hey, this isn't currently supported. We would really appreciate any patch or pull request adding support.

Closing as a duplicate of #85.

**Closed by kylef** 2015-01-31 22:28 UTC
