### ISSUE TITLE
Xcodeproj doesn't know about the following attributes {"alwaysOutOfDate"=>"1"}

### ISSUE THREAD

**Issue by brunophilipe** [CocoaPods/Xcodeproj#785] opened 2020-09-22 20:29 UTC
I get this error when trying to run `pod install` on my project.

This attribute is enabled by unchecking the "Based on dependency analysis" option in a "Run Script" build phase (see screenshot).

![Screen Shot 2020-09-22 at 22 26 54](https://user-images.githubusercontent.com/2136642/93934038-d572b000-fd22-11ea-9999-3410e0fdd230.png)

**Comment by dnkoutso** [comment] 2020-09-22 20:29
Looks like we need to add this to Xcodeproj. PRs welcome!

This is a warning by the way, its not an error.

**Comment by dnkoutso** [comment] 2020-09-22 20:30
Is this for Xcode 12?

**Comment by brunophilipe** [comment] 2020-09-22 20:34
I think so, but I'm not 100% sure.

**Comment by dnkoutso** [comment] 2020-09-22 20:34
It must be tbh...this seems new in Xcode 12.

**Comment by LemonSpike** [comment] 2020-09-29 16:44
I'd be interested in trying to resolve this bug as my first OS contribution, could I get some pointers @dnkoutso? I wanted to fix this for my own project, if it's not too hard.

**Comment by dnkoutso** [comment] 2020-09-29 16:48
It should be fairly easy. See sample PR for another attribute here https://github.com/CocoaPods/Xcodeproj/pull/716

**Comment by nicoburns** [comment] 2020-09-29 16:49
> This is a warning by the way, its not an error.

Are we sure this is just a warning? This setting is breaking `pod install`/`pod update` for me (cocoapods 1.9.3).

I get the following warning:
```
[!] [!] Xcodeproj doesn't know about the following attributes {"alwaysOutOfDate"=>"1"} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

But also the following error:
```
RuntimeError - [Xcodeproj] Unknown object version.
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:227:in `initialize_from_file'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:112:in `open'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1177:in `block (2 levels) in inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1176:in `each'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1176:in `block in inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1171:in `inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:106:in `analyze'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment] 2020-09-29 16:53
You are getting two things one warning and one error.

The error is fixed by `gem update xcodeproj`.

**Closed** 2020-10-09 01:20 UTC

**Comment by chadwiedemann** [comment] 2020-10-26 16:44
@nicoburns what was the root cause of that error?  I had the same problem.

**Comment by olegtatarciuc** [comment] 2020-11-06 08:44
`gem update xcodeproj` didn't fix it for me. 
I needed to go to `Build Phases` -> and select back `Based on dependency analysis` for the script where I previously deselected it.
Make `pod install` or `pod update` and after that, come back to `Build Phases` and deselect again the `Based on dependency analysis`.
